version: "3.8"

services:
  django:
    build:
      context: ./django-app
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./django-app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  fastapi:
    build:
      context: ./fastapi-app
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "5000:5000"
    volumes:
      - ./fastapi-app:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.6.3
    container_name: airflow_webserver
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/google-drive-apikey.json:/opt/airflow/google-drive-apikey.json
    depends_on:
      - db
    command: ["bash", "-c", "sleep infinity"]

  airflow-scheduler:
    image: apache/airflow:2.6.3
    container_name: airflow_scheduler
    depends_on:
      - db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/google-drive-apikey.json:/opt/airflow/google-drive-apikey.json
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: ["bash", "-c", "sleep infinity"]

  streamlit:
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit-app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  postgres_data:
  airflow_logs:
